### ISSUE TITLE
Docs Page Is All Spammy?

### ISSUE THREAD

**Issue by chriskol** [MacGapProject/documentation#11]
Not sure if this is still being maintained but docs.macgap.com gives me all sorts of spam when I go to it.

**Comment by jeff-h** [comment]
Wow, the spammers are annoying. I used to personally pay for the macgap.com domain, but since I haven't actually used the project personally for many years, and nothing was ever actually on the site, I cancelled the renewal. Someone else has registered it, and put in the redirect to spam that you're seeing.

PR's welcome to remove any links to them.

**Comment by chriskol** [comment]
Breaks my heart.  Loved this :(

**Comment by chriskol** [comment]
Breaks my heart. Loved this :(

Rather than removing the links, is there a github pages link we can replace it with?

**Comment by jeff-h** [comment]
Would you be interested in setting it up to work at macgap.github.com? That would be awesome! :)

**Comment by chriskol** [comment]
Change all docs.Macgap.com to macgap.GitHub.com? Because that redirects to
macgap.GitHub.io which gives a 404

On Nov 24, 2017 1:51 AM, "jeff-h" <notifications@github.com> wrote:

Would you be interested in setting it up to work as macgap.github.com? That
would be awesome! :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MacGapProject/documentation/issues/11#issuecomment-346748205>,
or mute the thread

**Comment by jeff-h** [comment]
Yeah, it's not currently set up to use GitHub pages. Would you be interested in doing that? https://pages.github.com

**Comment by chriskol** [comment]
Created #12 which I think is the first step in stopping the redirect to docs.macgap.com when you go to http://macgapproject.github.io/documentation/ .  Though I'm not sure as I haven't dealt with Jekyll before so feel free to reject if it's not the case.  I figure that's the first step before we re-edit all the links.  Not sure if something also needs to be changed in 'settings' for the repo as well.

**Comment by chriskol** [comment]
Created #13 now to update the links and baseurl.

Also, I went across the org and updated the spammy link to https://macgapproject.github.io/documentation/ across all repos.

**Comment by chriskol** [comment]
I think the last thing before closing this is that the Repo description needs to be changed.  It's currently "Documentation for MacGap. Visit http://docs.macgap.com" but should at least be "Documentation for MacGap. Visit https://macgapproject.github.io/documentation/" ?

I don't appear to have permission to be able to edit the description myself.

**Comment by jeff-h** [comment]
Thanks for all your good work sorting this out!
